name: RedCrafted-Mod
main: me.unraveledmc.unraveledmcmod.UnraveledMCMod
version: ${tfm.build.version}
description: Plugin for RedCrafted.
depend: [Aero, WorldEdit]
softdepend: [BukkitTelnet, UMC-Essentials, LibsDisguises]
authors: [Madgeek1450, Prozza, CreeperSeth, AwesomePinch(CreeperIvanYT), aggelosQQ, decyj145 and SaltShaker53]

# plugin.yml is no longer used to define commands.
